### 1) Import numpy as np, and pandas as pd

In [1]:
# your code here
import numpy as np
import pandas as pd

In [7]:
# leave this cell blank

### 2) Execute the next cell as-is to create a numpy array arr

In [2]:
np.random.seed(10)
arr = np.random.randint(-100, 100, (1, 35))
arr

array([[ -91,   25,  -85,  -36,   13,   23,   56,   57,   13,  -92,  -27,
        -100,  -60,   64,   15,  -84,    0,   39,  -46,  -12,    7,   22,
         -38,  -67,    0,   77,   79,  -46,  -23,   97,  -87,   53,   26,
          41,   -8]])

In [3]:
# leave this cell blank

### 3) Re-shape arr to have 5 rows and 7 columns; then print arr 
##### [note: after this manipulation arr should have 5 rows and 7 columns]

In [4]:
# your code here
arr=arr.reshape(5,7)
arr

array([[ -91,   25,  -85,  -36,   13,   23,   56],
       [  57,   13,  -92,  -27, -100,  -60,   64],
       [  15,  -84,    0,   39,  -46,  -12,    7],
       [  22,  -38,  -67,    0,   77,   79,  -46],
       [ -23,   97,  -87,   53,   26,   41,   -8]])

In [5]:
# leave this cell blank

### 4) Get column-wise means and put them in an array called cmean; then print cmean 
##### [note: pay attention to the axis!]

In [6]:
# your code here
cmean=np.mean(arr,axis=0)
print(cmean)

[ -4.    2.6 -66.2   5.8  -6.   14.2  14.6]


In [7]:
# leave this cell blank

### 5) Get column-wise standard deviations and put them in an array called csd; then print csd 
##### [note: pay attention to the axis!]

In [8]:
# your code here
csd=np.std(arr,axis=0)
print(csd)

[50.37459677 61.10515527 34.16079624 35.17612827 61.17188897 47.30073995
 40.97609059]


In [9]:
# leave this cell blank

### 6) Use arr, cmean, and csd to normalize the data using matrix manipulation and broadcasting; call the resulting array arrnorm; then print arrnorm

In [10]:
# your code here
arrnorm=(arr-cmean)/csd
print(arrnorm)


[[-1.72706097  0.36658118 -0.55033846 -1.18830588  0.31060018  0.1860436
   1.01034529]
 [ 1.21092781  0.17019841 -0.75525172 -0.93245055 -1.53665354 -1.56868582
   1.20558109]
 [ 0.37717423 -1.41722903  1.93789394  0.94382189 -0.65389513 -0.55390254
  -0.18547401]
 [ 0.51613316 -0.66442839 -0.02341866 -0.16488455  1.35683238  1.36995743
  -1.47891122]
 [-0.37717423  1.54487784 -0.6088851   1.34181908  0.5231161   0.56658733
  -0.55154115]]


In [ ]:
# leave this cell blank

### 7) Print column-wise means of arrnorm 
##### [note: these should all be ~0]

In [30]:
# your code here
mearrnorm=np.mean(arrnorm,axis=0)
print(mearrnorm)

[ 2.22044605e-17  4.44089210e-17  6.66133815e-17  8.88178420e-17
  2.22044605e-17 -2.22044605e-17  2.22044605e-17]


In [ ]:
# leave this cell blank

### 8) Print column-wise standard deviations of arrnorm 
##### [note: these will all be ~1]

In [31]:
# your code here
stdarrnorm=np.std(arrnorm,axis=0)
print(stdarrnorm)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# leave this cell blank

### 9) Convert arrnorm into a pandas dataframe called df with rows ['s1', 's2', 's3', 's4', 's5'] and columns ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']; then print df

In [12]:
# your code here
df = pd.DataFrame(arrnorm, index=['s1', 's2', 's3', 's4', 's5'] , columns=['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7'])
print(df)

          f1        f2        f3        f4        f5        f6        f7
s1 -1.727061  0.366581 -0.550338 -1.188306  0.310600  0.186044  1.010345
s2  1.210928  0.170198 -0.755252 -0.932451 -1.536654 -1.568686  1.205581
s3  0.377174 -1.417229  1.937894  0.943822 -0.653895 -0.553903 -0.185474
s4  0.516133 -0.664428 -0.023419 -0.164885  1.356832  1.369957 -1.478911
s5 -0.377174  1.544878 -0.608885  1.341819  0.523116  0.566587 -0.551541


In [13]:
# leave this cell blank

### 10) Create a new column in df called 'f8' as the sum of column 'f1' and column 'f3'; then print df
##### [note: afer this manipulation df should contain a new column called f8]

In [14]:
# your code here
df['f8'] = df['f1'] + df['f3']

print(df)

          f1        f2        f3        f4        f5        f6        f7  \
s1 -1.727061  0.366581 -0.550338 -1.188306  0.310600  0.186044  1.010345   
s2  1.210928  0.170198 -0.755252 -0.932451 -1.536654 -1.568686  1.205581   
s3  0.377174 -1.417229  1.937894  0.943822 -0.653895 -0.553903 -0.185474   
s4  0.516133 -0.664428 -0.023419 -0.164885  1.356832  1.369957 -1.478911   
s5 -0.377174  1.544878 -0.608885  1.341819  0.523116  0.566587 -0.551541   

          f8  
s1 -2.277399  
s2  0.455676  
s3  2.315068  
s4  0.492715  
s5 -0.986059  


In [ ]:
# leave this cell blank

### 11) Create a new column in df called 'f9' as the exponent of column 'f1'; then print df
##### [note: afer this manipulation df should contain a new column called f9]

In [37]:
# your code here
df['f9']=np.exp(df['f1'])
print(df)

          f1        f2        f3        f4        f5        f6        f7  \
s1 -1.727061  0.366581 -0.550338 -1.188306  0.310600  0.186044  1.010345   
s2  1.210928  0.170198 -0.755252 -0.932451 -1.536654 -1.568686  1.205581   
s3  0.377174 -1.417229  1.937894  0.943822 -0.653895 -0.553903 -0.185474   
s4  0.516133 -0.664428 -0.023419 -0.164885  1.356832  1.369957 -1.478911   
s5 -0.377174  1.544878 -0.608885  1.341819  0.523116  0.566587 -0.551541   

          f8        f9  
s1 -2.277399  0.177806  
s2  0.455676  3.356597  
s3  2.315068  1.458158  
s4  0.492715  1.675536  
s5 -0.986059  0.685797  


In [ ]:
# leave this cell blank

### 12) Drop columns f1 and f3 in df; then print df 
##### [note: after this manipulation, df should no longer contain columns f1 and f3]

In [38]:
# dropping columns
df.drop(['f1','f3'],axis=1,inplace=True)
print(df)# your code here


          f2        f4        f5        f6        f7        f8        f9
s1  0.366581 -1.188306  0.310600  0.186044  1.010345 -2.277399  0.177806
s2  0.170198 -0.932451 -1.536654 -1.568686  1.205581  0.455676  3.356597
s3 -1.417229  0.943822 -0.653895 -0.553903 -0.185474  2.315068  1.458158
s4 -0.664428 -0.164885  1.356832  1.369957 -1.478911  0.492715  1.675536
s5  1.544878  1.341819  0.523116  0.566587 -0.551541 -0.986059  0.685797


In [ ]:
# leave this cell blank

### 13) Execute the next cell as-is to create a new dataframe called dff

In [39]:
dff =  pd.DataFrame(np.random.randn(2, 7), index=['s6', 's7'], columns=['f2', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9'])
dff['f4'] = [np.nan, np.nan]
dff

f2  f4        f5        f6        f7        f8        f9
s6 -0.634254 NaN  1.996523 -1.118672  2.180328  0.190467  1.261686
s7  0.417660 NaN  0.047355 -0.608426 -0.268548 -0.666302 -0.344012

In [ ]:
# leave this cell blank

### 14) Append dff to df; then print df
##### [note: after this manipulation df should contain two new rows, s6 and s7]

In [40]:
# your code here
df=df.append(dff)
print(df)


          f2        f4        f5        f6        f7        f8        f9
s1  0.366581 -1.188306  0.310600  0.186044  1.010345 -2.277399  0.177806
s2  0.170198 -0.932451 -1.536654 -1.568686  1.205581  0.455676  3.356597
s3 -1.417229  0.943822 -0.653895 -0.553903 -0.185474  2.315068  1.458158
s4 -0.664428 -0.164885  1.356832  1.369957 -1.478911  0.492715  1.675536
s5  1.544878  1.341819  0.523116  0.566587 -0.551541 -0.986059  0.685797
s6 -0.634254       NaN  1.996523 -1.118672  2.180328  0.190467  1.261686
s7  0.417660       NaN  0.047355 -0.608426 -0.268548 -0.666302 -0.344012


In [ ]:
# leave this cell blank

### 15) Use fillna to replace NaNs in column f4 of df with 0s; then print df
##### [note: after this manipulation df should not contain any NaNs]

In [42]:
# your code here
df['f4']=df['f4'].fillna(value=0)
print(df)

          f2        f4        f5        f6        f7        f8        f9
s1  0.366581 -1.188306  0.310600  0.186044  1.010345 -2.277399  0.177806
s2  0.170198 -0.932451 -1.536654 -1.568686  1.205581  0.455676  3.356597
s3 -1.417229  0.943822 -0.653895 -0.553903 -0.185474  2.315068  1.458158
s4 -0.664428 -0.164885  1.356832  1.369957 -1.478911  0.492715  1.675536
s5  1.544878  1.341819  0.523116  0.566587 -0.551541 -0.986059  0.685797
s6 -0.634254  0.000000  1.996523 -1.118672  2.180328  0.190467  1.261686
s7  0.417660  0.000000  0.047355 -0.608426 -0.268548 -0.666302 -0.344012


In [ ]:
# leave this cell blank

### 16) Print the element at row s4 and column f6 in df

In [43]:
# your code here
print(df.loc['s4']['f6']) 

1.3699574270054844


In [ ]:
# leave this cell blank

### 17) Print the subsection of data in df containing rows s2 and s3, and columns f5 and f6 

In [44]:
# your code here
print(df.loc[['s2','s3']][['f5','f6']])

          f5        f6
s2 -1.536654 -1.568686
s3 -0.653895 -0.553903


In [ ]:
# leave this cell blank

### 18) Use masking and conditional selection to print only that data in df where column f4 is greater than column f5 

In [46]:
# your code here
print(df[df['f4']>df['f5']])


          f2        f4        f5        f6        f7        f8        f9
s2  0.170198 -0.932451 -1.536654 -1.568686  1.205581  0.455676  3.356597
s3 -1.417229  0.943822 -0.653895 -0.553903 -0.185474  2.315068  1.458158
s5  1.544878  1.341819  0.523116  0.566587 -0.551541 -0.986059  0.685797


In [ ]:
# leave this cell blank

### 19) Use the describe method to print basic statistics on df (count, mean, std deviation, etc)

In [47]:
# your code here
df.describe()


f2            f4        f5        f6        f7        f8  \
count  7.000000  7.000000e+00  7.000000  7.000000  7.000000  7.000000   
mean  -0.030942  6.344132e-17  0.291983 -0.246728  0.273111 -0.067976   
std    0.963502  9.128709e-01  1.182622  1.016160  1.245246  1.438558   
min   -1.417229 -1.188306e+00 -1.536654 -1.568686 -1.478911 -2.277399   
25%   -0.649341 -5.486675e-01 -0.303270 -0.863549 -0.410045 -0.826181   
50%    0.170198  0.000000e+00  0.310600 -0.553903 -0.185474  0.190467   
75%    0.392120  4.719109e-01  0.939974  0.376315  1.107963  0.474195   
max    1.544878  1.341819e+00  1.996523  1.369957  2.180328  2.315068   

             f9  
count  7.000000  
mean   1.181653  
std    1.199889  
min   -0.344012  
25%    0.431801  
50%    1.261686  
75%    1.566847  
max    3.356597

In [ ]:
# leave this cell blank

### 20) Use the corr method to print the correlation matrix of df

In [48]:
# your code here
print(df.corr())

          f2        f4        f5        f6        f7        f8        f9
f2  1.000000  0.047482 -0.072784  0.162272 -0.064858 -0.757884 -0.313101
f4  0.047482  1.000000  0.142773  0.225169 -0.439267  0.388614 -0.200997
f5 -0.072784  0.142773  1.000000  0.447648  0.007869 -0.223463 -0.391876
f6  0.162272  0.225169  0.447648  1.000000 -0.756434 -0.254206 -0.344103
f7 -0.064858 -0.439267  0.007869 -0.756434  1.000000 -0.152738  0.187826
f8 -0.757884  0.388614 -0.223463 -0.254206 -0.152738  1.000000  0.548579
f9 -0.313101 -0.200997 -0.391876 -0.344103  0.187826  0.548579  1.000000


In [ ]:
# leave this cell blank