In [2]:
# Reference: 
# online free docs:          https://pandas.pydata.org/pandas-docs/stable/
# book old edition free:  https://www.safaribooksonline.com/library/view/python-data-science/9781491912126/
# book new edition pay: https://smile.amazon.com/Python-Data-Science-Handbook-Essential/dp/1491912057/

In [3]:
# pandas is a python library used for data manipulation and analysis
# two key data structures - series objects and dataframes

In [1]:
import numpy as np
import pandas as pd

In [5]:
##### pandas series objects ####
# very similar to numpy arrays, but with axes labels (as denoted by index)

In [6]:
##### creating pandas series objects #####

In [8]:
# create a pandas series using a list with default indices
lst = [10, 20, 30]
ser = pd.Series(data=lst)
print(lst)
print(ser)

[10, 20, 30]
0    10
1    20
2    30
dtype: int64


In [6]:
# create a pandas series using a list with labeled indices
lst = [10, 20, 30]
idx = ['a', 'b', 'c']
ser = pd.Series(data=lst, index=idx)
print(ser)

a    10
b    20
c    30
dtype: int64


In [7]:
# create a pandas series using an array with default indices
arr = np.array([100, 200, 300])
ser = pd.Series(data=arr)
print(ser)
print(arr)

0    100
1    200
2    300
dtype: int32
[100 200 300]


In [9]:
# create a pandas series using an array with labeled indices
arr = np.array([100, 200, 300])
idx = ['x','y','z']
ser = pd.Series(data=arr, index=idx)
print(ser)
print(arr)

x    100
y    200
z    300
dtype: int32
[100 200 300]


In [11]:
# create a pandas series using a dictionary with labeled indices
dct = {'p':1000, 'q':2000, 'r':3000}
ser = pd.Series(data=dct)
ser

p    1000
q    2000
r    3000
dtype: int64

In [10]:
# you can give the series a name
ser = pd.Series(np.random.normal(size=3), index=['a','b','c'], name='X')
print(ser)
print()
print(np.random.normal(size=3))

a   -2.019794
b    1.129415
c   -0.717733
Name: X, dtype: float64

[0.83943571 0.12127115 3.00168469]


In [13]:
##### indexing pandas series #####

In [11]:
# index using default indices
ser = pd.Series(data=[10,20,30,40,50])
print (ser)
print (ser[2])

0    10
1    20
2    30
3    40
4    50
dtype: int64
30


In [2]:
# index using labeled indices
ser = pd.Series(data=[10,20,30,40,50],index=[2,3,4,5,6])
print (ser)
print (ser[2])
print (ser.iloc[2])

2    10
3    20
4    30
5    40
6    50
dtype: int64
10
30


In [16]:
# index using labeled indices
ser = pd.Series(data=[100,200,300,400,500], index=['p','q','r','s','t'])
print (ser)
print (ser['r'])
print (ser[2])

p    100
q    200
r    300
s    400
t    500
dtype: int64
300
300


In [20]:
ser = pd.Series(data=np.array([1,2,3,4,5,6]),index=[1,2,3,4,5,6])
print (ser)
print (ser[3])
print (ser.iloc[3])

1    1
2    2
3    3
4    4
5    5
6    6
dtype: int32
3
4
